Initial support for GraphQL.
ZaiusInc/node-sdk pull request #47
Opened 2022-01-28 02:38 UTC by vickrum

Since requests are routed through the v3 API, authentication is handled by the request interceptor by adding the `x-api-key` header.

A type must be provided in the call to `graphql` to describe the expected response.

https://zaius-jira.atlassian.net/browse/ZAIUS-14459

2022-01-28 09:37 UTC, SoAG approved these changes

2022-01-30 16:00 UTC, steelThread requested changes
Like i mentioned before team rey is going to make that version header default to 'graphql'.  so we don't need to specify the header.  when using this outside of a zip context it works just like any other apis, ie consumer using the sdk is required to supply `x-api-header`, however this is not required when being used in a zip app.

So the only thing that i don't like is that we can the `data.data` object navigation.  eg 

```typescript
const response = await z.graphql<QueryResult>('query', {});
const result = response.data.data; // <= :(
```

This is however consistent in that the ApiV3.HttpResponse wrapper is what is returned.  If data was optional in the ApiV3.HttpResponse we could have extended it but I guess instead we need something like this.

```typescript
export interface GqlHttpResponse<T extends Data> {
  success: boolean;
  status: number;
  statusText: string;
  headers: Headers;
  data?: T;
  errors?: Error[];
  extensions?: Extensions;
}

// then something like
export async function graphql<T extends Data>(query: string, variables?: { [key: string]: any })
  : Promise<GqlHttpResponse<T>> 
{
  const response = await ApiV3.post<Result<T>>('/graphql', { query, variables });
  const {data, extensions, errors} = response.data;
  return {...response, data, extensions, errors};
}

```
going to think about this a little today.

> *[Reviewable](https://reviewable.io/reviews/zaiusinc/node-sdk/47#-:-Muff3jf3am6EUczKx2T:byqnf71)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @steelThread and @vickrum)

___
*[src/Api/GraphQL/graphql.ts, line 15 at r1](https://reviewable.io/reviews/zaiusinc/node-sdk/47#-MufehGV7dbTLsLr84ki:-MufehGV7dbTLsLr84kj:b-bbyt9r) ([raw file](https://github.com/zaiusinc/node-sdk/blob/8f8189782c93033349b9c6e49d5315dd6b732d1b/src/Api/GraphQL/graphql.ts#L15)):*
> ```XML
>   variables?: { [key: string]: any }
> ): Promise<ApiV3.HttpResponse<Result<T>>> {
>   return ApiV3.request(
> ```

`return ApiV3.post('/graphql', {query, variables});`


<!-- Sent from Reviewable.io -->

2022-01-30 17:35 UTC, steelThread reviewed
Ok, here's where I landed on this (!!may not compile!!).  I added Gql to all the interfaces, you had a conflict with the native `Error` class.  I like this approach over what you had (which is consistent with the v3 apis) because the protocol is different that the V3 apis which always return a `data` field in responses, the gql spec doesn't afford us the opportunity to make it not optional.  Also, if you could document the interfaces using the descriptions from the spec (and links to it) that would be convenient for developers reading the docs.

```typescript
// Types.ts

export interface GqlExtensions {
  [key: string]: string;
}

export interface GqlError {
  message: string;
  locations: [
    {
      line: number;
      column: number;
    }
  ];
  extensions?: GqlExtensions;
}

export interface GqlHttpResponse<T extends ApiV3.V3Response> {
  success: boolean;
  status: number;
  statusText: string;
  headers: Headers;
  data?: T | null;  // undefined (not present in response) and null are both valid values from the spec
  errors?: GqlError[];
  extensions?: GqlExtensions;
}
```

```typescript
// graphql.ts
interface QueryResult<T extends ApiV3.V3Response> {
  errors?: GqlError[];
  data?: T;
  extensions?: GqlExtensions;
}

/**
 * Queries the GraphQL API.
 * @param query the GQL query
 * @param variables named variables to substitute into the query, if any
 * @returns {GqlHttpResponse} if successful
 * @throws {HttpError} if it receives a non-2XX result
 */
export async function graphql<T extends ApiV3.V3Response>(
  query: string,
  variables?: { [key: string]: any }
): Promise<GqlHttpResponse<T>> {
  const response = await ApiV3.post<QueryResult<T>>('/graphql', { query, variables });
  const {data, extensions, errors} = response.data;
  return {...response, data, extensions, errors};
}
```

> *[Reviewable](https://reviewable.io/reviews/zaiusinc/node-sdk/47#-:-Muft2HX4lrfD2dsdikr:b656zo7)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @steelThread and @vickrum)



<!-- Sent from Reviewable.io -->

2022-01-30 17:40 UTC, steelThread reviewed
Couple of other things:
* Bump the major version in the package json
* Add graphql to the exported z object in Api/index.ts.  that will expose it

> *[Reviewable](https://reviewable.io/reviews/zaiusinc/node-sdk/47#-:-Mug3NBm1D45qbetgYTT:bz82z2u)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @steelThread and @vickrum)



<!-- Sent from Reviewable.io -->

2022-02-01 01:02 UTC, steelThread approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zaiusinc/node-sdk/47#-:-MumnY8l7AmlCiSFotss:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mal)



<!-- Sent from Reviewable.io -->

2022-02-01 05:43 UTC, merged